image: python:3.10

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  PY_VER: "py310"

cache:
  paths:
    - "${PIP_CACHE_DIR}"

stages:
  - validate
  - test
  - build

before_script:
  - make install-deps

format:
  stage: validate
  script:
    - make format

lint:
  stage: validate
  needs:
    - format
  script:
    - make lint

security:
  stage: validate
  needs:
    - format
  script:
    - make security

test:
  stage: validate
  needs:
    - format
    - lint
    - security
  script:
    - make test
  artifacts:
    when: always
    reports:
      junit: junit-report.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

dist-build-publish:
  stage: build
  only:
    - tags
  needs:
    - format
    - lint
    - security
    - test
  variables:
    TWINE_USERNAME: gitlab-ci-token
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    REPO_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  before_script:
    - bash devops/scripts/build.sh
  script:
    - bash devops/scripts/dist-publish.sh

image-build-publish:
  stage: build
  only:
    - tags
  needs:
    - format
    - lint
    - security
    - test
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_NAME: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -f devops/Dockerfile -t ${IMAGE_NAME} .
    - sh devops/scripts/test-builds.sh ${IMAGE_NAME}
    - docker push ${IMAGE_NAME}
