image: python:3.9

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

validate-test:
  before_script:
    - pip install -r requirements/requirements-build.txt
  script:
    - make run-tox

dist-build-publish:
  stage: build
  needs: [validate-test]
  variables:
    TWINE_PASSWORD: ${CI_JOB_TOKEN}
    TWINE_USERNAME: gitlab-ci-token
    REPO_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  script:
    - make build-dist
    - twine upload --verbose --skip-existing --non-interactive --repository-url ${REPO_URL} dist/*

image-build-publish:
  stage: build
  needs: [validate-test]
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -f devops/Dockerfile -t ${IMAGE_TAG} .
    - docker push ${IMAGE_TAG}
