version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  run-tox-py310:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install -y graphviz
      - run:
          name: Install requirements
          command: pip install -r requirements/requirements-build.txt
      - run:
          name: Run tests for py310
          command: tox -e py310
  run-tox-py311:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install -y graphviz
      - run:
          name: Install requirements
          command: pip install -r requirements/requirements-build.txt
      - run:
          name: Run tests for py311
          command: tox -e py311

workflows:
  run-tox:
    jobs:
      - run-tox-py310
      - run-tox-py311
