version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements/requirements-build.txt
      - run:
          name: Run tests
          command: make run-tox

workflows:
  build-and-test:
    jobs:
      - build-and-test
