version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  run-tox-py38:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements/requirements-build.txt
      - run:
          name: Run tests for py38
          command: tox -e py38
  run-tox-py39:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements/requirements-build.txt
      - run:
          name: Run tests for py39
          command: tox -e py39
  run-tox-py310:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements/requirements-build.txt
      - run:
          name: Run tests for py310
          command: tox -e py310
  run-tox-py311:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install requirements
          command: pip install -r requirements/requirements-build.txt
      - run:
          name: Run tests for py311
          command: tox -e py311

workflows:
  run-tox:
    jobs:
      - run-tox-py38
      - run-tox-py39
      - run-tox-py310
      - run-tox-py311
